blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/Tuntii/KayaDB/discussions
    about: Please ask and answer questions here.
  - name: Documentation
    url: https://tuntii.github.io/KayaDB/
    about: Check the official docs first.
