[package]
name = "kaya-client"
description = "Official async Rust client library for KayaDB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
kaya-core.workspace = true
kaya-net.workspace = true
tokio.workspace = true

[lib]
path = "src/lib.rs"
