[package]
name = "kaya-client"
description = "Official async Rust client library for KayaDB"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
rust-version.workspace = true

[dependencies]
kaya-core.workspace = true
kaya-net.workspace = true
tokio.workspace = true
kaya-sim = { workspace = true, optional = true }

[features]
default = []
tls = ["kaya-net/tls"]
trace = ["dep:kaya-sim"]
